apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.fetcher.name }}
  namespace: {{ .Values.environment }}
  labels:
    app: {{ include "crypto-arp-tracker.name" . }}-fetcher-{{ .Values.environment }}
spec:
  replicas: {{ .Values.fetcher.replicas }}
  selector:
    matchLabels:
      app: {{ include "crypto-arp-tracker.name" . }}-fetcher-{{ .Values.environment }}
  template:
    metadata:
      labels:
        app: {{ include "crypto-arp-tracker.name" . }}-fetcher-{{ .Values.environment }}
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command: ['sh', '-c', 'until nc -z -v -w60 db 5432; do echo "Waiting for postgres db...."; sleep 3; done;']
      containers:
        - name: fetcher-app
          image: "{{ .Values.fetcher.image.repository }}:{{ .Values.fetcher.image.tag }}"
          env:
            - name: PG_DB
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretsName }}
                  key: PG_DB
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretsName }}
                  key: PG_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgres.secretsName }}
                  key: PG_PASSWORD
            - name: PYTHONPATH
              value: "."
          resources:
            requests:
              memory: "64Mi"
              cpu: "500m"
            limits:
              memory: "128Mi"
              cpu: "1"
          startupProbe:
            exec:
              command:
                - sh
                - -c
                - "fetcher/healthcheck.sh"
            initialDelaySeconds: 10
            failureThreshold: 30
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "fetcher/healthcheck.sh"
            initialDelaySeconds: 30
            periodSeconds: 30
