version: '3.8'

services:
  arp_fetcher:
    build: ./fetcher
    image: arp_fetcher:v0.0.1
    container_name: arp_fetcher
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
    depends_on:
      - db
    restart: always
    networks:
      - arp_bridge
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - arp_bridge
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER}"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  db_data:

networks:
  arp_bridge:
    driver: bridge
