apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.fetcher.name }}
  namespace: {{ .Values.environment }}
spec:
  selector:
    app: {{ include "crypto-arp-tracker.name" . }}-fetcher-{{ .Values.environment }}
  ports:
    - port: {{ .Values.service.fetcher.port }}
      targetPort: {{ .Values.service.fetcher.targetPort }}
  type: ClusterIP
