apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.visualizer.name }}
  namespace: {{ .Values.environment }}
spec:
  selector:
    app: {{ include "crypto-arp-tracker.name" . }}-visualizer-{{ .Values.environment }}
  ports:
    - port: {{ .Values.service.visualizer.port }}
      targetPort: {{ .Values.service.visualizer.targetPort }}
  type: LoadBalancer
