apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
  labels:
    app: db
    env: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
