apiVersion: v1
kind: Service
metadata:
  name: fetcher-app
  labels:
    app: fetcher-app
    env: prod
spec:
  selector:
    app: fetcher-app
    env: prod
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP