apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-lb
      env: prod
  template:
    metadata:
      labels:
        app: nginx-lb
        env: prod
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - name: http
            containerPort: 80
          - name: https
            containerPort: 443
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "1"
            ephemeral-storage: "150Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
