apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    app: nginx-lb
    env: prod
spec:
  selector:
    app: nginx-lb
    env: prod
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  type: LoadBalancer
