apiVersion: apps/v1
kind: Deployment
metadata:
  name: visualizer-app
  labels:
    app: visualizer-app
    env: prod
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 10
  selector:
    matchLabels:
      app: visualizer-app
      env: prod
  template:
    metadata:
      labels:
        app: visualizer-app
        env: prod
    spec:
      containers:
      - name: visualizer-app
        image: stunnyman/arp-visualizer:latest
        env:
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: PG_DB
        - name: PG_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: PG_USER
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: PG_PASSWORD
        - name: PYTHONPATH
          value: "."
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "500m"
            ephemeral-storage: "100Mi"
          limits:
            memory: "128Mi"
            cpu: "1"
            ephemeral-storage: "150Mi"
        startupProbe:
          httpGet:
            path: "/health"
            port: 8000
          initialDelaySeconds: 10
          failureThreshold: 30
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 20